title: Nicholas Mutsaerts
description: Microsoft System Administrator | Tier 2 Support | Windows 11 & MacOS Support Specialist | End-User Training | Security & Compliance

logo: /images/headshot_circle.png

#description: Theme
theme: jekyll-theme-minimal
show_downloads: false

# GitHub settings
github:
  is_project_page: false
